# Generated by Django 6.0.6 on 2026-06-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellibrary',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modellibrary',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
