# Generated by Django 6.0.6 on 2026-06-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sertifika Adı')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Veren Kurum')),
                ('issue_date', models.DateField(verbose_name='Veriliş Tarihi')),
                ('document', models.FileField(upload_to='certificates/', verbose_name='Belge / Görsel')),
                ('verification_link', models.URLField(blank=True, null=True, verbose_name='Doğrulama Linki')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sitede Görünür')),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
                'ordering': ['-issue_date'],
            },
        ),
    ]
