# Generated by Django 6.0.6 on 2026-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issued_by_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Veren Kurum'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_by_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Veren Kurum'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sertifika Adı'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Sertifika Adı'),
        ),
    ]
