# Generated by Django 6.0.6 on 2026-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(help_text='Otomatik olarak doldurulabilir veya manuel yazılabilir. (Örn: taktik-simulasyon)', unique=True, verbose_name='URL İsmi (Slug)')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Resim')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='products/models/', verbose_name='3D Model Dosyası (.glb/.gltf)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created_at'],
            },
        ),
    ]
